name: Build
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        java:
          - 8
          - 17
          - 21
        jvm_flag:
          - "-XX:+UseG1GC"
          - "-XX:+PrintGCDetails"
          - "-XX:MaxHeapSize=512m"
          - "-XX:+UnlockExperimentalVMOptions"
          - "-XX:ConcGCThreads=2"
    fail-fast: false
    name: "Test JDK ${{ matrix.java }}, OS: ${{ matrix.os }}, Flag: ${{ matrix.jvm_flag }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'

      - name: Log JVM Flag
        run: |
          echo "Running with JVM flag: ${{ matrix.jvm_flag }}"
      

      - name: Maven Compile
        env:
          MAVEN_OPTS: ${{ matrix.jvm_flag }}
        run: mvn -X compile -B --file pom.xml

      - name: Maven Verify
        env:
          MAVEN_OPTS: ${{ matrix.jvm_flag }}
        run: mvn -X verify -B --file pom.xml

      - name: Run tests with coverage
        env:
          MAVEN_OPTS: ${{ matrix.jvm_flag }}
        run: |
          mvn test jacoco:report
